#let inset_value = (
  bottom: 0.5em,
)
#set block(inset: inset_value)
#set par(leading: 1.2em)
= Einleitung

Das Thema Layoutanalyse erweckte mein Interesse, da ich mich bereits in einem Webdesign-Kontext mit der Darstellung historischer Texte und Inhalte beschäftigte. Und dort spielt, in Bedienung wie Darstellung, das Scrollen natürlich eine Rolle: Wir wischen und scrollen uns heute durch endlose Bänder von Hypertext, und was einmal als eine Art maschinengetriebene „Magie" beschrieben wurde, ist längst zur alltäglichsten Form geworden, in der wir digitalen Medien begegnen.#footnote[vgl. @Hartnell_J_2020_Continuous_Scrolls[S. 8]] Dass ausgerechnet diese Geste eine sehr alte Verwandte hat – die Buchrolle der Antike –, macht Jack Hartnell zum Ausgangspunkt eines ganzen Sammelbandes, der den Bogen bezeichnenderweise „from Papyrus to Hypertext" spannt.#footnote[vgl. @Hartnell_J_2020_Continuous_Scrolls] Vor diesem Hintergrund wird die Erforschung des Layouts antiker _bookscrolls_ zu einem durchaus anziehenden Thema – jedenfalls dann, um es vorsichtig auszudrücken, wenn man ohnehin eine Arbeit zur Epoche des Altertums schreiben muss. So entstanden Fragen aus quasi-professionellem Interesse. Wie haben es die ganz alten Meister gemacht?

Auf den ersten Blick sehen die Kolumnen in literarischen Papyrusrollen wie in Platte E des Papyrus 9782 der Berliner Papyrussammlung#footnote[@BerlPap_9782 Sofern bei Online-Quellen nichts Genaueres angegeben wird, wurden alle Links zuletzt am 10.07.2026 geprüft. Platte E ist auch dem Anhang beigefügt.] ganz konventionell und gut lesbar aus. Die Kolumnen sind angenehm schmal, Zeilenabstände relativ großzügig. Die Abstände zwischen den Kolumnen sind recht breit. Was einem heutigen Leser an der Gestaltung zuerst auffallen mag, womit man aber im Geschichtsstudium auf jeden Fall vertraut gemacht wird, sind fehlende Worttrennungen auch bekannt als _scriptio continua_. Ebenso vermisst man hier Absätze. Die Literatur musste mich allerdings erst noch auf etwas hinweisen, worauf moderne Texte, Textverarbeitung und -darstellung in der Regel nicht ausgelegt sind. Die leichte Schrägheit der Spalten war genauso gewollt, wie es auf dem Bild erscheint. Es war nicht die Ungenauigkeit oder Sorglosigkeit des Schreibers, die dazu führte, dass die Spalte Zeile für Zeile leicht nach links abdriftet, sondern der Schreiber legte das Layout bewusst so an.

Einer der wichtigsten Fundorte für Buchrollen wie P. 9782 ist der Ort Oxyrhynchus in Ägypten#footnote[vgl.  @Pleiades_Oxyrhynchus und @DNP_Papyri_literarisch_RWG] und der Papyrologe William Johnson veröffentlichte 2004 eine Monographie über die Schreiber und Buchrollen von Oxyrhynchus, in der er anhand der reichhaltigen Funde des Ortes das Layout von literarischen Papyri und speziell das Phänomen der schrägen Kolumnen, bekannt als _Maas's Law_, ausführlich behandelte.#footnote[@Johnson_WA_2004_Bookrolls; 1993 machte er schon mit den Oxyrhynchus-Papyri auf die Intentionalität des Phänomens aufmerksam, vgl. dazu @Johnson_WA_1993_Maas_Ruling_Dots; 2009 war Johnson auch für das Kapitel zu Buchrollen in @Bagnall_RS_2009_Oxford_Papyrology[S. 256ff] verantwortlich; Des Weiteren betreibt er eine Website zu dem Thema: https://ancientbooks.papyrology.org/] Für dieses Thema, und dementsprechend die folgende Arbeit, ist dieses Werk also von großer Bedeutung. Ein Makel den Susan Stephens jedoch an Johnsons ansonsten wichtigem Beitrag zur Erforschung antiker Buchproduktion sah, war, dass seine Daten, händisch gemessen, ohne Zugang zu den Papyri schwer nachzuprüfen seien.#footnote[vgl. @Stephens_S_2005_Bookrolls_Review] Digitale Layoutdaten, die mit Faksimiles verknüpft sind, können in Zukunft dieser Problematik vorbeugen.

Durch meine Erfahrung mit dem Transkriptionsprogramm Transkribus#footnote[#link("https://www.transkribus.org/")] wusste ich sofort, als ich auf P. 9782 gestoßen bin, dass ich mit der Anwendung die Layoutdaten des Papyrus digital erschließen und auswerten kann. Bevor ich aber darüber schreibe, wie ich das gemacht habe und welche Probleme sich dabei ergaben, gehe ich kurz darauf ein, was eine Buchrolle ist und wie sie aussieht, und wie es um Maas's Law in der Forschung steht. Am Ende möchte ich meine Messwerte mit der vergangenen Bearbeitung dieses Papyrus und den generell in Buchrollen zu erwartenden Werten vergleichen.

= Forschungsstand und Quelle

== Die Antike Buchrolle als Textträger

Papyrus war der wichtigste Beschreibstoff der Antike; von etwa 300 v. Chr. bis rund 700 n. Chr. wurden griechische Texte in Ägypten auf Papyrus geschrieben und aufbewahrt. Der trockene Wüstensand bot die idealen Konservierungsbedingungen, um die vergessenen Rollen über viele Jahrhunderte zu erhalten.#footnote[vgl. @DNP_Papyri_literarisch_RWG]

=== Material und Konstruktion der Buchrolle

Gewonnen wurde der Beschreibstoff aus der vor allem in Ägypten heimischen Papyrusstaude: Das Mark des dreieckigen Stängels wurde in dünne Streifen geschnitten, überlappend ausgelegt und mit einer zweiten, quer dazu verlaufenden Lage bedeckt. Durch Pressen oder Schlagen verbanden sich die Fasern, wobei der austretende Pflanzensaft das entstehende Vlies verfestigte und die Oberfläche verleimte; anschließend wurde das getrocknete Blatt geglättet und poliert. Für die spätere Verwendung als Rolle ist eine Materialeigenschaft entscheidend: Papyrus ist zwar überaus fest und langlebig, zugleich aber spröde. Er eignet sich deshalb nicht zum Falten, wohl aber zum Rollen.#footnote[vgl. @Material-Archiv_Papyrus]

Das einzelne Papyrusblatt wird in der Papyrologie als _Kollema_ bezeichnet, die Klebeverbindung zwischen zwei Blättern als _Kollesis_.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 88]] Durch das Aneinanderkleben von bis zu zwanzig solcher Bögen entstand das lange Band, das die fertige Rolle bildete.#footnote[vgl. @Material-Archiv_Papyrus; @Johnson_WA_2004_Bookrolls[S. 86–87]] Wurde beim Kopieren eines Textes das Ende einer Rolle erreicht, wurde eine weitere angeklebt und der unbeschriebene Rest am Schluss abgeschnitten. Verstärkte Bögen am Anfang und gegebenenfalls am Ende beugten dem Ausfransen vor. Verglichen mit dem Kodex war die Herstellung einfach: Es entfielen komplizierte Lagenstrukturen, das Nähen der Bindung und das Anbringen von Buchdeckeln; zur Ausstattung eines Schreibers gehörten dementsprechend nur Papyrus, Feder, Tinte, Schwamm, Messer und Kleber.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 86–87]]

Die Breite der Kollemata war zugleich ein Qualitätsmerkmal: Je breiter ein Bogen, desto höher wurde die Qualität der Rolle geschätzt.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 88]] Johnson zitiert Plinius den Älteren (nat. hist. 13,78–81), wenn er eine repräsentative Auswahl von Oxyrhynchus Papyri mit Blattbreiten von 20–24 cm als _optimae chartae_ – als hochwertig aber nicht als das Beste vom Bestem – einstuft. Solche hochwertigen Rollen wurden dann mit einer ordentlichen Schrift beschrieben.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 88–90]]

=== Schrift und Layout der Buchrolle

Die Buchrolle wurde horizontal ausgerollt und von links nach rechts spaltenweise beschrieben. Der Text der Spalten, bzw. _Kolumnen_, wurde meistens in einer auf Qualität zielenden und gut lesbaren Buchschrift verfasst, in der die Buchstaben weitestgehend getrennt waren. In einem zeitgenössischen Kontext würden wir Druckschrift sagen. Wenige erhaltene Exemplare wurden in einer Schreibschrift oder qualitativ minderwertigeren Schrift geschrieben. Die Schrift war, wie bereits angemerkt, _scriptio continua_ ausgeführt. Satzeichen wurden nicht in dem Umfang verwendet, den wir heute gewohnt sind. Zeichen, die eine dem Komma ähnliche Funktion hatten, gab es gewöhnlicherweise nicht und wenn eher als nachträgliche Annotation. Satzenden und Sprecherwechsel in Dialogen und Dramen wurden durchaus markiert. Eine absatzartige Trennung zwischen Abschnitten wurde meistens mit einem _Paragraphos_, einer horizontalen Linie am linken Rand einer Kolumne, ausgezeichnet. Befand sich die Trennung innerhalb der Zeile, wurde dort zusätzlich ein Punkt `·` zwischen den Wörtern eingesetzt. Ein weiteres Textstrukturzeichen ist eine Art spitzes Anführungszeichen `>`, die Diple.#footnote[vgl. @Johnson_WA_2009_Ancient_Book[S. 257–261]; Paragraphos und Diple sind auf dem Bild oben in Spalte 3 gut zu erkennen.]

Mit Blick auf die Konstruktion der Rolle ist noch erwähnenswert, dass die Schreiber es nicht vermieden, über eine Kollesis hinweg zu schreiben; die vorgegebene Breite von Kolumne zu Kolumne war ihnen offenbar wichtiger als die Rücksicht auf die Klebestellen.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 88]] Die Merkmale dieser oft sehr akkurat angelegten Kolumnen werden im Folgenden kurz angesprochen.

Da die Rolle keine Seiten kennt, ist die zentrale Einheit der Layoutanalyse nicht die Seite oder das Kollema, sondern die einzelne Kolumne.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 86]] Unter Layout sei hier – mit dem Typolexikon – die „grafische Anordnung einzelner Text- und Bildelemente" verstanden.#footnote[@Layout_Typolexikon] Aus den Kolumnen leiten sich die Bezugsgrößen ab: der _Kolumnenzwischenraum_ (intercolumn) als Abstand zwischen zwei benachbarten Kolumnen sowie die Fläche von Kolumne zu Kolumne, die von der linken Kante der einen bis zur linken Kante der nächsten reicht. Sinnvoll bemessen lassen sich zudem nur der obere und der untere Rand der Rolle. Ein linker und rechter Rand je Kolumne wäre angesichts der fortlaufenden Aneinanderreihung der Spalten keine aussagekräftige Größe.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 86]] Auf dieser Grundlage lässt sich eine Kolumne durch eine überschaubare Zahl von Maßen beschreiben: Breite und Höhe der Kolumne, ihre Fläche als Produkt beider sowie Höhe und Länge der gesamten Rolle.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 100–143]] Eben diese Maße bilden später den Gegenstand der hier vorgestellten Erfassung.

Bei den konkreten Größenverhältnissen ist Vorsicht geboten, weil ältere Faustregeln der Kodikologie nicht ohne Weiteres auf die Rolle übertragbar sind. So gilt die vom Kodex her bekannte Regel, der untere Rand verhalte sich zum oberen wie 3:2, für die Buchrolle nicht; typische Werte liegen bei etwa 3–4 cm oben und 3–5 cm unten.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 131–140]] Auch das vermeintliche Bild der Luxusrolle trügt: Eine _édition de luxe_ zeichnet sich nicht durch besonders hohe Kolumnen aus, sondern durch ein eher schmales Schriftband bei mittlerer Rollenhöhe, große Schrift und auffällig breite Ränder.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 155–156]] Die Kolumnenbreite schließlich hängt weniger vom literarischen Genre ab, als ältere Beobachtungen nahelegten. Die Annahme z. B., Rednertexte seien durchweg schmaler gesetzt, bestätigt sich statistisch nicht. Eine Ausnahme bilden die philosophischen Texte, die breite Kolumnen tendenziell meiden.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 152–155]] Ein Gestaltungsmerkmal der Kolumnen weicht allerdings so systematisch von der zu erwartenden rechtwinkligen Anordnung ab, dass es eine eigene Betrachtung verlangt.

== Maas's Law

Als _Maas's Law_ wird die Beobachtung bezeichnet, dass der linke – und tendenziell auch der rechte – Rand einer Kolumne nicht exakt senkrecht steht, sondern sich Zeile für Zeile leicht nach links unten verschiebt, sodass die Kolumne sozusagen die Form eines Parallelogramms annimmt.#footnote[vgl. @Johnson_WA_1993_Maas_Ruling_Dots[S. 211]] Der Name geht auf den Altphilologen und Byzantinisten Paul Maas (1880–1964) zurück, dem Johnson die allgemeine Beobachtung des Phänomens zuschreibt.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 91] Zur Person von Maas: @NDB_Paul_Maas[S. 597]]

=== Sorglosigkeit oder Intention?

Wie wenig selbstverständlich die spätere Umdeutung war, zeigt der Blick auf die ältere Bewertung. Bereits die Erstedition der hier untersuchten Rolle durch Diels und Schubart aus dem Jahr 1905 nimmt die Neigung wahr, deutet sie aber im Rahmen einer an gedruckten Büchern geschulten Erwartung. Gemessen am senkrechten Satzspiegel sei es „schon eher als ein Mangel der Handschrift zu betrachten", dass „hin und wieder die seitlichen Ränder etwas von der Senkrechten abweichen".#footnote[@BKT_II_1905[S. VI]] Bemerkenswerterweise erkennen die Herausgeber im selben Atemzug, dass das Hauptbestreben des Schreibers einem gleichmäßigen Anblick der Schriftsäulen galt. Die Abweichung wird also durchaus gesehen, aber als Unvollkommenheit verbucht, nicht als Absicht.#footnote[vgl. @BKT_II_1905[ebd.]]

Diese Deutung kehrte Johnson um. In einem Aufsatz von 1993, ausgearbeitet dann in seiner Monographie von 2004, legte er die erste Quantifizierung des Phänomens vor.#footnote[vgl. @Johnson_WA_1993_Maas_Ruling_Dots[S. 211]; @Johnson_WA_2004_Bookrolls[S. 91–92]] An über 150 messbaren Kolumnen aus Oxyrhynchus – in der erweiterten Stichprobe von 2004 knapp 200 – zeigte sich, dass sich die deutliche Mehrheit, rund drei Viertel, um etwa 1° bis 4° nach links neigt, während eine aufrechte Kolumne die Ausnahme bildet und ein Ausschlag nach rechts nahezu nicht vorkommt.#footnote[vgl. @Johnson_WA_1993_Maas_Ruling_Dots[S. 211]] Gegen die Vermutung, die Schräge sei ein mechanischer Fehler – etwa Folge des Schreibens auf dem Knie –, führte Johnson an, dass die Neigung nicht beliebig, sondern systematisch nach links ausfällt, und deutete sie als bewussten ästhetischen Effekt.#footnote[vgl. @Johnson_WA_1993_Maas_Ruling_Dots[S. 212]] Gestützt wird diese These durch die von ihm beschriebenen _ruling_ bzw. _alignment dots_, Punktreihen, die parallel zum geneigten linken Rand verlaufen und teils vor dem Schreibvorgang angelegt worden sein müssen.#footnote[vgl. @Johnson_WA_1993_Maas_Ruling_Dots[S. 212–214]]

=== Erwähnungen in jüngerer Forschung

In der Folge wurde Maas's Law vielfach registriert, in der Regel unter Verweis auf Johnsons Monographie und meist ohne weitere Prüfung.#footnote[vgl. @Obbink_D_2014_Sappho[S. 32, 47]; @Falivene_MR_2011_Diegeseis_Papyrus[S. 87]; @Del_Corso_L_2024_Literary_Papyri_Bodleian[S. 4]; @AIP_2022_Guidelines_for_Editing_Papyri[S. 26]] Einen von Johnson unabhängigen, experimentellen Beleg lieferte 2023 eine Untersuchung mit Makro-Röntgenfluoreszenz (MA-XRF) an ausgerollten Herkulaneum-Papyri: Sie wies bleigezeichnete Hilfslinien nach, mit denen die Schreiber das Kolumnenlayout vor dem Beschreiben anlegten. Da diese vertikalen Hilfslinien selbst leicht nach links geneigt und nachweislich vor dem Text gezogen sind, ist die Schrägstellung als bewusste, geplante Praxis erwiesen und zeigt sich zugleich chronologisch wie geografisch weit verbreitet.#footnote[vgl. @Romano_FP_2023_Layout_Lead; @Pleiades_Herculaneum]

So gut das Phänomen inzwischen als intentionales Gestaltungsmerkmal abgesichert ist, so wenig ist es bislang Gegenstand einer teilautomatisierten Messung geworden. Johnson maß den Winkel des linken Randes gegen die Schriftzeile mit Lineal und Winkelmesser am Original, Stück für Stück.#footnote[vgl. @Johnson_WA_1993_Maas_Ruling_Dots[S. 211]] Erste Schritte zu einer digitalen Erfassung materieller Merkmale unternimmt neuerdings das halbautomatische _Measurement Tool_ von Causo, das Höhe, Breite, Ränder, Zeilenhöhe und -abstand sowie Kollemata am kalibrierten Digitalbild bestimmt.#footnote[vgl. @Causo_S_2025_Measurement_Tool[S. 260–265]] Ein Verfahren, das die Neigung, und mit ihr die übrigen Layoutmerkmale, an einer literarischen Buchrolle aus digitalen Reproduktionen gewinnt, liegt damit weiterhin nicht vor. Genau hier setzt die vorliegende Arbeit an.

== Die Quelle: Papyrus 9782

=== Beschreibung des Dokuments

Die Quelle dieser Arbeit ist Papyrus 9782 aus der Berliner Papyrussammlung. Die Rolle wurde in der Ruine eines Hauses in Eschmunen bzw. Hermopolis – etwa 80 km südlich von Oxyrhynchus – gefunden, 1901 in Kairo erworben und 1905 von Diels und Schubart ediert. Sie schätzen die Entstehungszeit der Rolle auf das zweite Jahrhundert. Der Text ist ein Kommentar zu Platons Theaitet.#footnote[vgl. @BKT_II_1905[S. V, VIII] Zu Name und Lage des Fundorts vgl. @Pleiades_Hermopolis. Zur Lage von Oxyrhynchus vgl. @Pleiades_Oxyrhynchus] Den Editoren zufolge handle es sich bei dieser Rolle um ein schönes, gut erhaltenes Buch aus gutem Material mit so sorgfältigen Klebungen, dass die Kollesis oft schwer erkennbar sei. Die Höhe der Rolle betrage etwa 30 cm und die Kolumnen seien etwa 20 cm hoch, womit oben und unten ein "stattlicher" Rand verbleibe, was wohl für die Editoren das Urteil unterstreicht, dass damit ein "gutes Buchhändlerexemplar vorliegt". Die Kolumnen beschreiben sie als schmal und gleichmäßig, nur diese von der Senkrechten abweichende Ausrichtung der Spalten wird von ihnen noch als Mangel ausgelegt. Der 2–3 cm breite Zwischenraum der Kolumnen und die Ränder seien selten für Verbesserungen genutzt worden. Übliche Zeichen wie Paragraphos und Diple seien vorhanden.#footnote[vgl. @BKT_II_1905[S. VI–VII & X]; Diple werden "Schlusshaken" und "Anführungshaken" genannt.] Was den Umfang der Rolle angeht, sei die vorhandene Rolle 6 m lang. Die Editoren zählen darin 76 Kolumnen, wobei sie den Anfang vermissen. Die Edition zählt 74 Kolumnen, die bruchstückhaft oder vollständig vorhanden sind. Die Kolumnen mit den Nummern 72 und 76 wurden von den Editoren teilweise rekonstruiert, indem sie Zitate am Ende der vorrausgehenden Kolumnen fortsetzten. Darauf folgen noch die kleinen Fragmente 1–4, die auf Plate T zu sehen sind.#footnote[vgl. @BKT_II_1905[S. V–VI u. 47–51]]

Die Fragmente haben lagerungsbedingte Löcher, die offensichtlich während des aufgerollten Zustands entstanden sind. Dementsprechend wiederholen sich alle paar Zentimeter die Muster der Löcher, wo die Stellen aufgerollt übereinander lagen. In den Faksimiles ist dann zu sehen, dass die Löcher am Anfang der Rolle kleiner sind und enger beieinander liegen und der Abstand sich nach hinten hinaus stetig vergrößert, sowie die Löcher immer größer werden. Das legt den Schluss nahe, dass der Anfang der Rolle innen lag, da der Papyrus dort besser geschützt ist. Diels und Schubart haben natürlich in ihrer Edition auch angemerkt, dass das Buch "falsch zusammengerollt" worden sei.#footnote[@BKT_II_1905[S. V]]

=== Bisher verfügbare Daten

Metadaten und Digitalisate zum Papyrus finden sich in der Berliner Papyrusdatenbank.#footnote[@BerlPap_9782] Es gibt einen Eintrag im Portal Trismegistos der KU Leuven.#footnote[@TM_62580] Die Trismegistos Nummer 62580 ist nicht Teil von William Johnsons Datensatz.#footnote[vgl. @Johnson_WA_2025_Physical_Features] Metadaten und eine digitalisierte Transkription gibt es auf papyri.info.#footnote[@PapyriInfo_TM_62580] Die TEI-XML kodierte Edition, deren Text auf papyri.info präsentiert wird, befindet sich auf Github.#footnote[@DCLP_62580] Dem Dokument ist zu entnehmen, dass es 2014 nach Version 5 der EpiDoc Guidelines für die Auszeichnung von antiken Werken bearbeitet wurde.#footnote[Zur aktuellen Version 9.8: @EpiDoc_Guidelines.] Das TEI-XML verzeichnet keine Layoutinformationen in einem `facsimile`-Element#footnote[Die aktuellen EpiDoc Guidelines sehen, wie hier https://epidoc.stoa.org/gl/latest/supp-images.html dokumentiert, durchaus die Verwendung des Elements vor.], aber immerhin dokumentiert es die 2011–2013 stattgefundene Digitalisierung kolumnenweise. In einem Element `custodialHist` gibt es mit Jahresangabe versehene Einträge als `custEvent` für jede Kolumne, jeweils mit Link zum entsprechenden Bild der Berliner Papyrusdatenbank.#footnote[vgl. @DCLP_62580] Damit bestünde das Potential, Transkription und systematisch erfasste Layoutdaten zusammenzuführen. Allerdings sind nicht alle Digitalisate, die es auf der Webseite der Berliner Papyrusdatenbank gibt, verlinkt. Darüber hinaus gibt es bei den Digitalisaten auch auf der Berliner Webseite eine Lücke. Im Anhang befindet sich ein Versuch der Zuordnung, soweit die Platten. Ich konnte kein METS-XML oder IIIF-Manifest finden, das eine Aufstellung der mit dem Dokument verknüpften Digitalisate enthalten würde.

= Datenerfassung in Transkribus

Für die Layoutauszeichnung verwendete ich die Webapp Transkribus.#footnote[@ReadCoop_Transkribus Die Transrkibussammlung ist mit diesem Einladungslink zugänglich: #link("https://app.transkribus.org/invitations/c22ceb11-967c-4cda-b82a-6453340cc983"). Stand: 09.07.2026.] Transkribus erlaubt die strukturelle Auszeichnung und Transkription von Dokumenten. Entscheidend für mich war, dass ich dort auf jedem Digitalisat, die Layoutstrukturen mit Polygonen, also Figuren bestehend aus verbundenen Punkten, nachzeichnen konnte. Nach meinen Erfahrungen muss ich allerdings, genauso wie Causo vorweg auch darauf hinweisen, dass die Messungen an Digitalisaten mit gewissen Verzerrungen einhergehen können.#footnote[vgl. @Causo_S_2025_Measurement_Tool[S. 257]] Dazu später mehr im Detail. Leider ist Transkribus nicht speziell darauf ausgerichtet, die zuvor beschriebenen Elemente einer Buchrolle zu erfassen. Aber auch Causos Tool war in der 2025 veröffentlichten Vorstellung noch limitiert; so war es z. B. nicht möglich, mehrere Textbereiche auf einem Bild zu erfassen.#footnote[vgl. @Causo_S_2025_Measurement_Tool[S. 269]] Die Einstellungsmöglichkeiten von Transkribus erlaubten mir jedoch, Anpassungen vorzunehmen, um eine hinreichende Lösung für meine Zwecke zu erzielen.#footnote[Letztendlich wäre vermutlich auch ein handelsübliches Programm zur Erstellung von Vektorgrafiken wie Inkscape (https://en.wikipedia.org/wiki/Inkscape) für diesen manuellen Teil der Arbeit praktikabel.]

Grundsätzlich kann man in Transkribus Textregionen und, innerhalb dieser, Zeilen erfassen. Diese Elemente lassen sich typisieren. Die vorhandenen Kolumnen markierte ich zunächst als Textregion mit einem einfachen Viereck, wobei die Eckpunkte des Polygons so gut es ging den gedachten Eckpunkten der Textspalten entsprechen sollten. Dabei sollte die untere Kante an der Grundlinie der letzten Zeile anliegen und die obere Kante auf der oberen Zeile aufliegen, parallel zu deren Grundlinie. Die linke Kante sollte nach bestem Willen so ausgerichtet sein, wie man einen Winkelmesser auf einem physischen Dokument anlegen würde. Gleiches gilt für die rechte Kante. Die linken Seiten der Kolumnen sind allerdings etwas gerader, da sich der Schreiber hier ganz an seinem Layout orientieren konnte. Am rechten Ende der Zeilen, musste er natürlich Zugeständnisse an die Form des letzten Buchstabens, oder die korrekte Worttrennung machen, weshalb die rechten Seiten der Kolumnen etwas ausgefranster sind. Zeilen habe ich auf den ersten beiden Platten mit einfachen Linien aus Start- und Endpunkten markiert. Ausführlichere Zeilenmarkierung und das auf mehreren Seiten, wäre ein sehr großer Aufwand gewesen.#footnote[Ich testete auch die automatische Regionenerkennung von Transkribus, für die ich zuvor ein Modell mit den Markierungen der 55 nutzbaren Kolumnen trainiert habe. Für eine grobe Erkennung der Spalten funktionierte das Modell relativ gut. Die Polygone hatten aber viele Punkte, die nicht gerade eng anliegend waren, mit denen keine Messung der Neigung, Höhe, Breite etc. zu machen war. Die Standardzeilenerkennung von Transkribus funktionierte an P 9782 außerordentlich schlecht, indem sie sehr wenige Zeilen überhaupt erkannt hat. Hier versuchte ich kein gesondertes Modelltraining, da ich ähnliche Ungenauigkeiten wie bei den Regionen erwartete.]

Für die Kolumnen legte ich zwei Typen fest: `column` und `column_unusable`. Letzterer war für Kolumnen gedacht, die zu stark beschädigt waren oder auch aufgrund der Ausrichtung des Fragments auf dem Digitalisat keine vernünftige Messung der Schräge erlauben würden. Den Eindruck einer übermäßigen Krümmung hatte ich bei der ersten Kolumne auf #link("https://berlpap.smb.museum/Original/P_09782-Pl-G1_R_001.jpg")[Platte G1], die meiner Meinung nach durch einen langen Riss entlang der oberen Hälfte zustandekommen konnte. Zeilen, die mir aufgrund von Beschädigungen nicht für die Auswertung geeignet schienen, markierte ich mit einem generischen Typ `damaged`.

Ebenso wie Causo markierte ich die integrierten Skalen, um unabhängig von den Metadaten der Bilddateien die Pixel in Zentimeter umrechnen zu können.#footnote[vgl. @Causo_S_2025_Measurement_Tool[S. 260–261]] Die Digitalisate enthielten eine Skala, die nicht als Beilage mit den Fragmenten fotografiert, sondern digital eingefügt wurde. Sie verläuft in fast allen Bildern auf ganzer Länge am unteren Rand. Platte H ist hier leider die Ausnahme, da sie keine Skala enthält. Wo sie vorhanden war markierte ich pro Bild jeweils 10 cm mit einer Region, der ich den Typ `scale_10_cm` gab.

Anders als Causo#footnote[vgl. @Causo_S_2025_Measurement_Tool[S. 260–261]] habe ich die Fragmente nicht mit einer Bounding Box#footnote[Eine Bounding Box ist ein einfaches lotrechtes Rechteck, das den obersten, untersten, und die am weitesten links und rechts liegenden Punkte eines Objektes einspannt.] eingerahmt, um Höhe und Breite des Fragments messen zu können. Ich verwarf den Versuch, eine große Textregion als Bounding Box über das ganze Fragment zu ziehen. Einerseits weil es eigentlich keine Textregion ist, andererseits weil Transkribus Probleme macht, wenn Textregionen sich einander überlappen.#footnote[Stand Juni 2026: Wenn eine Textregion Zeilen enthält und man dann eine neue Textregion darüber zieht, frisst die neue Region die Zeilen der bereits vorhandenen.] Stattdessen ließ ich mir von einem KI-Agenten ein Skript schreiben, das den Schritt automatisieren sollte; ich komme später darauf zurück. Platte H machte mir hier aber auch Probleme, da das Skript bei ihr nicht so erfolgreich war. Als Notlösung platzierte ich für diese Platte 4 kleine Textregionen `bounding_box_edge` an den äußersten Enden des Fragments.

= Datenverarbeitung mit Python

Die Verarbeitung der Daten erfolgt automatisch per Python.#footnote[Dieser Teil der Arbeit profitierte in erheblichem Maße von den Codegenerierungsfähigkeiten eines KI-Agenten.] Das Vorgehen ist modular aufgebaut: Kein einzelnes Skript erledigt alles, vielmehr durchläuft die Auswertung mehrere aufeinander aufbauende Schritte, die sich ein gemeinsames Datenformat teilen. Rückgrat ist eine zentrale JSON-Datei, in der die Layoutdaten Platte für Platte gesammelt werden. Jeder Schritt liest diese Datei ein, ergänzt seine Ergebnisse und schreibt sie zurück, wobei bereits vorhandene Einträge – etwa manuell gesetzte Werte – erhalten bleiben. So lässt sich die Verarbeitung jederzeit anhalten, einzelne Schritte wiederholen und der Zwischenstand nachvollziehen.

Im ersten Schritt werden die in Transkribus erfassten Layoutdaten aus dem exportierten PAGE-XML ausgelesen und in die JSON-Struktur überführt. Pro Platte erfasst das Skript die Bildmaße, die aus der markierten Zehn-Zentimeter-Region abgeleitete Skala von Pixeln zu Zentimetern sowie eine daraus geschätzte Auflösung. Die einzelnen Regionen werden anhand ihres in Transkribus vergebenen Typs getrennt – Kolumnen auf der einen, Fragmente auf der anderen Seite –, sodass die nachgezeichneten Polygone anschließend in maschinenlesbarer Form vorliegen.

Der zweite Schritt ergänzt jene Maße, die sich nicht aus den Polygonen, sondern nur aus dem Digitalisat selbst gewinnen lassen: die äußeren Abmessungen des Fragments. Dazu wird das auf einem Leuchttisch fotografierte Fragment per Bilderkennung vom hellen Hintergrund getrennt und in eine Binärmaske überführt, aus der sich die umschließende Bounding-Box als Blattmaß ableiten lässt. Nebenbei fällt ein einfaches Fragmentierungsmaß ab, nämlich die Zahl zusammenhängender Maskenteile. Wo die automatische Segmentierung scheiterte – bei Platte H –, greift der bereits beschriebene manuelle Ersatz. Zur Kontrolle erzeugt der Schritt für jede Platte ein Vorschaubild mit eingezeichneter Bounding-Box.

Auf dieser Grundlage berechnet der dritte Schritt die eigentlichen Layoutmerkmale. Ein Modul ermittelt zunächst die vergleichsweise unkomplizierten Maße je Kolumne – Höhe, Breite und Fläche – sowie den Abstand zwischen den Kolumnen und den Abstand von Kolumnenkante zu Kolumnenkante. Ebenso werden der obere und untere Rand und das Verhältnis von Schriftspiegel zu Blattfläche bestimmt; diese Werte laufen bewusst erst nach der Bounding-Box, weil sie das Blattmaß als Bezugsgröße voraussetzen.

Den Kern der Auswertung bildet die Messung der Kolumnenneigung, also von Maas's Law. Gemessen wird die linke Kante jeder nutzbaren Kolumne gegen eine Senkrechte – allerdings in drei Varianten, weil die Wahl der Bezugssenkrechten das Ergebnis maßgeblich beeinflusst. Die erste Variante nimmt schlicht die Bild-Senkrechte an. Die zweite korrigiert eine mögliche globale Schieflage der Platte im Digitalisat, indem sie die aus allen Oberkanten gemittelte Ausrichtung als Bezug verwendet. Die dritte orientiert sich schließlich an den tatsächlichen Schriftzeilen und kommt damit Johnsons ursprünglichem Vorgehen am nächsten, das den Winkel zwischen linkem Rand und Schriftzeile bestimmte#footnote[vgl. @Johnson_WA_1993_Maas_Ruling_Dots[S. 211]]; sie steht nur dort zur Verfügung, wo auch die Zeilen erfasst wurden. Ein positives Vorzeichen bedeutet dabei, dass die untere Kante gegenüber der oberen nach links versetzt ist – die Kolumne also, wie von Maas's Law erwartet, nach links kippt.

Der letzte Schritt fasst die so gewonnenen Werte in einem lesbaren Überblick zusammen. Aus der JSON-Datei wird eine Markdown-Übersicht erzeugt, die je Platte die Zahl der Kolumnen und Fragmente, die Blattmaße, Zeilenkennzahlen und die gemessenen Neigungswinkel ausweist und dieselben Kennzahlen über alle Platten hinweg aggregiert. Diese Übersicht bildet die Grundlage für die anschließende Besprechung der Ergebnisse.

= Ergebnisse

Ausgewertet wurden 55 nutzbare Kolumnen auf 14 Platten; die Fragmente der Platte T sowie stark beschädigte Einzelkolumnen bleiben außen vor. Die vollständigen Werte je Kolumne und je Platte finden sich in den Tabellen im Anhang./*TODO: Tabellen layout_per_column und layout_summary_per_plate einbinden*/

== Kolumnengeometrie und Neigung

Die Maße der Kolumnen fallen über die gesamte Rolle bemerkenswert einheitlich aus. Die Kolumnen sind durchgängig rund 20,5 cm hoch und etwa 5,5 cm breit, wobei die Breite kaum je 6 cm überschreitet. Zwischen zwei Kolumnen liegt ein Zwischenraum von etwa 2,6 cm, der Abstand von linker Kante zu linker Kante der nächsten Kolumne beträgt rund 8,1 cm. Das Blatt selbst ist zwischen etwa 29 und 31,5 cm hoch, im Mittel also rund 30 cm. Auf die Schrift entfallen davon etwa zwei Drittel: Das Verhältnis von Kolumnenhöhe zu Blatthöhe liegt bei rund 0,68. Der obere Rand misst etwa 3 bis 4,5 cm, der untere durchgängig mehr, nämlich etwa 5 bis knapp 7 cm. Diese Gleichmäßigkeit über Dutzende von Kolumnen hinweg deckt sich mit Johnsons Beobachtung, dass hinter der statistischen Einheitlichkeit solcher Rollen eine strenge handwerkliche Ausbildung steht.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 157–158]]

Die gemessene Kolumnenneigung bestätigt Maas's Law deutlich. Die plattenweiten Mittelwerte gegen die Bild-Senkrechte liegen zwischen 1,6° und 4,0° und damit genau in dem von Johnson genannten Bereich von etwa 1° bis 4°.#footnote[vgl. @Johnson_WA_1993_Maas_Ruling_Dots[S. 211]] Die Neigung fällt fast durchgängig positiv aus, die Kolumnen kippen also wie erwartet nach links; ein Ausschlag nach rechts kommt nicht vor. Nur die stark fragmentierten Platten R und S liegen mit rund 0,7° darunter. Diese Werte schmälern das Bild nur wenig in Anbetracht der wenigen nutzbaren Kolumnen und der starken Fragmentierung.

== Abgleich mit der Erstedition und die Frage der _édition de luxe_

Die digital gewonnenen Maße bestätigen die Angaben, die Diels und Schubart 1905 durch Autopsie am Original ermittelten, in erstaunlicher Genauigkeit. Ihre Blatthöhe von etwa 30 cm, die Schrifthöhe von 20,5 cm, die als „schmal" und „selten mehr als 6 cm breit" beschriebenen Kolumnen sowie der Kolumnenzwischenraum von 2–3 cm decken sich fast auf den Zentimeter mit den hier gemessenen Werten.#footnote[vgl. @BKT_II_1905[S. VI–VII]] Dass eine Messung am Digitalisat zu praktisch denselben Ergebnissen führt wie die Messung am physischen Objekt, ist zugleich ein Beleg für die Tragfähigkeit des Verfahrens.

Ob es sich um eine _édition de luxe_ handelt, lässt sich an Johnsons Kriterien nur vorsichtig beantworten. Eine Luxusrolle zeichnet sich bei ihm nicht durch besonders hohe Kolumnen aus, sondern durch ein schmales Schriftband bei mittlerer Rollenhöhe und auffällig breite Ränder.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 131–140 u. 155–156]] Mehrere dieser Merkmale sind gegeben: die Kolumnen sind mit rund 5,5 cm schmal, die Rollenhöhe von etwa 30 cm ist mittleren Zuschnitts, und besonders der untere Rand fällt mit bis zu knapp 7 cm großzügig aus. Die eigentlich markanten Schwellen – ein oberer Rand über 6 cm oder ein unterer über 7 cm – werden jedoch nicht ganz erreicht. Das schmale Schriftband passt überdies zu Johnsons Beobachtung, dass philosophische Texte breite Kolumnen meiden.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 152–155]] Insgesamt liegt damit eine hochwertige Handschrift mit mehreren Luxusmerkmalen vor, die aber eher das von Diels und Schubart vergebene Urteil eines „guten Buchhändlerexemplars" trägt als das einer vollen _édition de luxe_.

== Zur Wahl der Bezugssenkrechten

Der Vergleich der drei Messvarianten erlaubt einige methodische Beobachtungen. Ist ein Fragment im Digitalisat lotrecht ausgerichtet, genügt bereits die einfache Bild-Senkrechte für brauchbare Ergebnisse. Das zeigt sich an Platte D, deren geschätzte Plattenschiefe bei 0,0° liegt und bei der die Neigung gegen die Bild-Senkrechte und gegen die aus den Oberkanten gemittelte Ideal-Horizontale mit jeweils 3,1° zusammenfällt. Ähnlich verhält es sich bei der großen Platte H: Ihre elf Kolumnen liefern eine besonders robuste Ideal-Horizontale, die mit 2,5° kaum von den 2,3° gegen die Bild-Senkrechte abweicht (Plattenschiefe −0,2°). Beides spricht dafür, dass die Digitalisate im Regelfall gut ausgerichtet sind.

Auf den Platten A und B, auf denen ich zusätzlich die Zeilen erfasst habe, lässt sich die aus den Oberkanten gewonnene Horizontale gegen die tatsächliche Schrifthorizontale prüfen. Beide liegen nah beieinander – die Neigung gegen die Ideal-Horizontale (1,9° bzw. 2,2°) und gegen die Baseline nach Johnson-Methode (1,6° bzw. 1,9°) unterscheiden sich nur wenig, ebenso die plattenweite Oberkanten- und Baseline-Schiefe. Die Oberkanten allein liefern also schon eine tragfähige Horizontale, sodass die aufwendige Markierung sämtlicher Zeilen für die Neigungsmessung nicht zwingend erforderlich ist.

Eine Ausnahme bildet Kolumne 2 der Platte A. Hier fällt die gegen die eigene Baseline gemessene Neigung mit 0,1° aus dem Rahmen, während die übrigen Kolumnen der Platte Baseline-Werte um 1,6° bis 2,1° zeigen und dieselbe Kolumne gegen die Bild-Senkrechte noch 2,1° aufweist. Dafür kommen zwei Erklärungen in Betracht. Zum einen können die Zeilen einer einzelnen Kolumne für sich genommen zu schief stehen, um eine verlässliche Horizontale zu ergeben. Zum anderen – und das halte ich für wahrscheinlicher – könnte die untere Hälfte des Fragments physisch so verbogen sein, dass die unteren Zeilen leicht abfallen und die Baseline dieser Kolumne verzerren. Ein vergleichbarer Fall ist die erste Kolumne der Platte G1, die ich wegen eines langen Risses entlang der oberen Hälfte und der daraus folgenden Krümmung von vornherein von der Winkelmessung ausgeschlossen habe.

Allgemein gilt, dass auf allen Platten mit größeren Löchern und Rissen kleinere Abweichungen allein aus der Ausrichtung und Wölbung der Fragmente entstehen können. Die Neigungswerte sind daher nicht als exakte Winkel einzelner Kolumnen misszuverstehen, sondern als hinreichend genaue Näherung, deren Verlässlichkeit mit dem Erhaltungszustand der jeweiligen Platte steht und fällt.

= Fazit

Das Layout des Papyrus 9782 bestätigt einen Eindruck, der sich mit Johnsons Beobachtungen an zahlreichen literarischen Papyri deckt: Die räumliche Anordnung der Kolumnen dient nicht der inhaltlichen Gliederung des Textes, sondern folgt in erster Linie ästhetischen Gesichtspunkten und der Lesbarkeit. Die _scriptio continua_ und das Fehlen von Absätzen sprechen ebenso dafür wie der Umstand, dass die inhaltliche Strukturierung eigenen Zeichen – Paragraphos, Diple und Korrekturzeichen am Rand – zufällt, nicht aber der Anordnung der Spalten. Nur gelegentlich – wie in der dritten Kolumne von Platte H – machte der Schreiber der Rolle einen Absatz.

Das prominenteste Merkmal dieser Gestaltung, die von Maas beschriebene und von Johnson quantifizierte Schrägstellung der Kolumnen, ist auch an P. 9782 klar messbar und liegt mit plattenweiten Mittelwerten von etwa 1° bis 4° genau im erwarteten Bereich.#footnote[vgl. @Johnson_WA_2004_Bookrolls[S. 91–92]] Darüber hinaus bestätigen die digital gewonnenen Maße die Angaben, die Diels und Schubart 1905 durch Autopsie ermittelten, nahezu auf den Zentimeter. Gemessen an Johnsons Kriterien und im Einklang mit Diels und Schubart handelt es sich um eine hochwertige Handschrift mit mehreren Luxusmerkmalen – schmales Schriftband, großzügige Ränder.

Damit erweist sich zugleich das digitale Verfahren als tragfähig. Dass die Messung am Digitalisat praktisch dieselben Werte liefert wie die Messung am physischen Objekt, ist das beste Argument für seine Verlässlichkeit und zugleich eine Antwort auf Susan Stephens' Einwand, Johnsons handgemessene Daten seien ohne Zugang zu den Papyri kaum nachprüfbar.#footnote[vgl. @Stephens_S_2005_Bookrolls_Review] Mit hinreichend genau markierten Layoutdaten lassen sich brauchbare Maße erschließen, die für andere leicht überprüfbar und nachnutzbar sind. Der Vergleich der drei Bezugssenkrechten zeigt überdies, dass die Anforderungen an das Ausgangsmaterial nicht übertrieben hoch sind: Ist ein Fragment ungefähr lotrecht ausgerichtet, genügt bereits die Bildsenkrechte, und die aus den Oberkanten gemittelte Horizontale ist so tragfähig, dass nicht zwingend jede einzelne Zeile markiert werden muss.

Die Grenzen des Vorgehens sind dabei nicht zu übersehen. Die Untersuchung stützt sich auf ein einziges Objekt; das Nachzeichnen der Polygone bleibt eine manuelle, subjektive und aufwendige Arbeit; physische Wölbungen und Löcher können die Messung verzerren, wie die zweite Kolumne der Platte A und die von vornherein ausgeschlossene erste Kolumne der Platte G1 zeigen. Hinzu kommt, dass nur JPEG-Digitalisate zur Verfügung standen und der Platte H die eingefügte Skala fehlt. Schließlich beruht die rechnerische Umsetzung in erheblichem Maße auf einem KI-Agenten, sodass ich die zugrunde liegenden Gleichungen nicht in jedem Detail selbst verifizieren kann.

Gerade das Skalenproblem der Platte H ließe sich allerdings umgehen. Da die reale Höhe der Kolumnen über die gesamte Rolle hinweg bemerkenswert konstant bei rund 20,5 cm liegt, könnte man diese durchschnittliche Zentimeterhöhe auf die durchschnittliche, in Pixeln gemessene Kolumnenhöhe der Platte H übertragen und daraus deren fehlenden Umrechnungsfaktor gewinnen. Auf diesem Weg ließen sich auch die absoluten Maße der Platte H – Blatthöhe, -breite und Ränder – nachträglich rekonstruieren, obwohl ihr eine eigene Skala fehlt.

Über den vorliegenden Fall hinaus weist das Verfahren in mehrere Richtungen. Das halbautomatische _Measurement Tool_ von Causo könnte, sobald es seine derzeitigen Beschränkungen überwindet, einen wertvollen Beitrag zu einer breiter angelegten, vergleichbaren Erfassung leisten.#footnote[vgl. @Causo_S_2025_Measurement_Tool] Ebenso lohnend wäre es, systematisch erhobene Layoutdaten mit den bereits vorhandenen Transkriptionen und Faksimiles zu verknüpfen, wozu etablierte Standards wie TEI und IIIF bereitstehen.